language: bash

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:

    # set the environment variable CURRENT_DIR
    - CURRENT_DIR=`pwd`

    # add MATLAB to the path
    - if [ "$ARCH" == "Linux" ]; then
          export PATH="$PATH:$ARTENOLIS_SOFT_PATH/MATLAB/$MATLAB_VER/bin";
      fi

    # change to the current directory
    - cd $CURRENT_DIR

    # rename the cloned folder
    - cd .. && cp -r $NODE_LABELS COBRA && cd COBRA

    # launch the tests
    - bash .artenolis/runtests.sh

    # clean up the build directory
    - cd .. && rm -rf COBRA

    # clean up the tmp folder
    - rm -rf ~/tmp

after_success:
    - if [ "$ARCH" == "Linux" ]; then $ARTENOLIS_SOFT_PATH/julia/$JULIA_VER/bin/julia --color=yes -e 'cd(Pkg.dir("COBRA")); using Coverage; tmp=process_folder(); Codecov.submit(tmp, verbose=false); Coveralls.submit(tmp);'; fi

    # set environment variables for documentation deployment
    - if [[ "$ARCH" == "Linux" && "$JENKINS_PULL_REQUEST" != "True" ]]; then
        export TRAVIS_BRANCH=$GIT_BRANCH;
        export TRAVIS_PULL_REQUEST=false;
        var=$GIT_URL; export TRAVIS_REPO_SLUG=${var:7:${#var}};
        export TRAVIS_OS_NAME="linux";
        export TRAVIS_JULIA_VERSION=$JULIA_VER;
        $ARTENOLIS_SOFT_PATH/julia/$JULIA_VER/bin/julia --color=yes -e 'cd(Pkg.dir("COBRA")); include(joinpath("docs", "makeDoc.jl"))';
      fi
